# Generated by Django 5.0.7 on 2024-08-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_course_student_enrolled_courses_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_url',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_images/default_placeholder.jpg', upload_to='course_images/'),
        ),
    ]
