# Generated by Django 5.0.7 on 2024-08-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_number',
            field=models.PositiveIntegerField(),
        ),
    ]
